### PR TITLE
Release 2.0.2

### PR DESCRIPTION
**Pull request by eternoendless**
Changes:

- Add badges into README #99
- Prevent double escaping module descriptions #101
- Fix links when the module is disabled #102
- Update short description and logo #103
- Fix phpstan on latest PrestaShop #106

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
@eternoendless @PierreRambaud could you please assign it to me :pray:

**Comment by hibatallahAouadni** [comment]
Hello @eternoendless 

I encountred two issues:

### Issue n°1:
When I upgrade the module, the button stay in the state **Upgrade**, it chould be change to **Disable** (see the attached screen record below)

https://drive.google.com/file/d/11rEGtLJLt-z1zFKcLUa2_bUZmR1uKE0D/view

### Issue n°2:
After disabling the module, BO>CONFIGURE>Modules>Modules Catalog:
- the page is displayed => OK 
- but the menu is not active => NOK (see the attached screen record below)

https://drive.google.com/file/d/1DVlUvsADOxBZ7TLrUsiuPYnHozQ68yrD/view

I will create two issues about these bugs.
Thanks!

**Comment by eternoendless** [comment]
@hibatallahAouadni I believe both issues are common to all modules. You need to refresh the page for changes to apply (including menu items)

**Comment by hibatallahAouadni** [comment]
Hello @eternoendless 

As you can see in the attached screen record I upgraded the **LinkList** module, the button has been refreshed and changed to **Configure**, then I disabled it and access to **Module Catalog** and the menu is perfectly active:

https://drive.google.com/file/d/17fJXloYzjQZbzs49mW8eNCa-NagiYEsP/view

So both issues are not common to all modules.

Thanks!

**Comment by matks** [comment]
Hello

So @PierreRambaud and I have been exploring these 2 bugs.

## Bug 1: on Modules list, after upgrade from v2.0.1 to v2.0.2, the main button stay in the state Upgrade instead of Disable

@PierreRambaud has verified what is the logic that chooses whether or not to display "Upgrade" or something else. 📚 

Apparently what the code does is that it checks the latest version on addons.prestashop.com

So when you upgrade from v2.0.1 to v2.0.2, you see Upgrade instead of Disable _not because of a bug_ but because the version of your module is v2.0.2 and the latest version on addons.prestashop.com is v2.0.1 . So your Core "thinks" you need to upgrade (and it shows you the "Upgrade" button) because your version and the addons version mismatch 🤯 

This behavior is not something that is related to the scope of v2.0.2

🎉 **When we validate and release v2.0.2, this behavior will be fixed because addons version will be 2.0.2** 🎉 

## Bug 2: on Modules list, after disable v2.0.2, the "Modules Catalog" link in the menu is not updated

First, it's important to remember that MBO modules _controls and modifies_ this "Modules Catalog" link. When MBO is not installed, the "Modules Catalog" link is `admin-dev/index.php/improve/modules/catalog`. When MBO is installed it overrides this link and put `admin-dev/index.php/module/addons/modules/catalog` instead.

I am not sure to understand what you demonstrate in your first video.

_Theoretically, when we disable a module, this does not refresh the page._ So the link is not updated immediately. As explained by @eternoendless  you need to refresh your page to see the correct link.

> As you can see in the attached screen record I upgraded the LinkList module, the button has been refreshed and changed to Configure, then I disabled it and access to Module Catalog and the menu is perfectly active:

You have verified the behavior with Linklist module but "Modules Catalog" link _is not modified/controlled/overriden_ by Linklist module. This is why when you disable Linklist module you see the "Modules Catalog" link is OK. There is no relation between Linklist module and "Modules Catalog" link.

AFAIK this behavior is not something that is related to the scope of v2.0.2 ✅ 

You can observe other issues between MBO and "Modules Catalog" link for with current version of MBO (v2.0.1)
- Go to Modules > Modules manager
- Disable MBO module
- DONT Refresh the page 😉 
- link "Modules > Module catalog" is not modified yet
In https://github.com/PrestaShop/PrestaShop/issues/21588

**Comment by hibatallahAouadni** [comment]
Hello everyone,

LGTM, QA :heavy_check_mark:

**Comment by PierreRambaud** [comment]
Thank you everyone

**Comment by abramofranchetti** [comment]
Thankyou for logging this issue. Save me hours of work!

**Pull request merged**
